import 'package:flutter/rendering.dart';

const green = Color(0xFF29BB89);
const white = _white;
const red = _red;
const dark = _dark;
const grey = _grey;
const iron = _iron;
const whiteSmoke = _whiteSmoke;
const greyText = _greyText;
const whiteGrey = _whiteGrey;
const blackGrey = _blackGrey;
const blue = _blue;
const shuttleGrey = _shuttleGrey;
const bGrey = _bGrey;
const orang = _orang;
const iconGrey = _iconGrey;
const imageB = _imageB;
const contColor = _containerColor;

const _white = Color(0xffFFFFFF);
const _dark = Color(0xff0C161D);
const _red = Color(0xffff0000);
const _grey = Color(0xffE7E7E8);
const _greyText = Color(0xff979797);
const _iron = Color(0xffCCCECF);
const _whiteSmoke = Color(0xffF7F7F7);
const _whiteGrey = Color(0xffD8DCDE);
const _blackGrey = Color(0xff555555);
const _iconGrey = Color(0xff828282);
const _blue = Color(0xffFD4242);
const _bGrey = Color.fromARGB(31, 229, 226, 226);
const _orang = Color(0xffF4903A);
const _shuttleGrey = Color(0xff606469);
const _imageB = Color(0xffd9d9d9);
const _containerColor = Color(0xff1D2733);
