// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFIykHyhjKhQ3X2z0imiFrOAJCh1YWpE',
    appId: '1:7551035257:web:ff209f15bb3a25cd71f1a8',
    messagingSenderId: '7551035257',
    projectId: 'delivery-bot-29094',
    authDomain: 'delivery-bot-29094.firebaseapp.com',
    storageBucket: 'delivery-bot-29094.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwkp1f-YzkhBO5Y9kHRqdP0N5ppsf6eE',
    appId: '1:7551035257:android:6c958d312c12120171f1a8',
    messagingSenderId: '7551035257',
    projectId: 'delivery-bot-29094',
    storageBucket: 'delivery-bot-29094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA5vkH4a7HwwXzaJOiew5upTCMAKbcv70',
    appId: '1:7551035257:ios:8b93f0c86629344971f1a8',
    messagingSenderId: '7551035257',
    projectId: 'delivery-bot-29094',
    storageBucket: 'delivery-bot-29094.appspot.com',
    iosClientId: '7551035257-7ccrc1dap0emq3hqfmmiuuv5l8a2ltbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.botDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA5vkH4a7HwwXzaJOiew5upTCMAKbcv70',
    appId: '1:7551035257:ios:dd93da815bb1e95b71f1a8',
    messagingSenderId: '7551035257',
    projectId: 'delivery-bot-29094',
    storageBucket: 'delivery-bot-29094.appspot.com',
    iosClientId: '7551035257-tmf4kssol8cskacvfs4c2vhji9om2rhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.botDelivery.RunnerTests',
  );
}
